# config for Brewery.jar


# -- Settings --
# Defaults are written in []

# Languagefile to be used (found in plugins/Brewery/languages)
language: en

# If the player wakes up at /home when logging in after excessive drinking (/home plugin must be installed!) [true]
enableHome: true

# Type of the home-teleport: ['cmd: home']
# bed = Player will be teleported to his spawn bed
# 'cmd: home' = /home will be executed by the player. He has to have permissions for it without any delay!
# 'cmd: spawn' = /spawn will be executed by the player.
# 'cmd: whatever' = /whatever will be executed by the player.
homeType: 'cmd: home'

# If the player "wakes up" at a random place when offline for some time while drinking (the places have to be defined with '/brew Wakeup add' through an admin)
# The Player wakes at the nearest of two random places of his world [true]
enableWake: true

# If the Player may have to try multiple times when logging in while extremely drunk [true]
enableLoginDisallow: true

# If the Player faints shortly (gets kicked from the server) if he drinks the max amount of alcohol possible [false]
enableKickOnOverdrink: false

# If the Player vomits on high drunkeness (drops item defined below) [true]
# The item can not be collected and stays on the ground until it despawns.
enablePuke: true

# Item that is dropped multiple times uncollectable when puking [SOUL_SAND]
pukeItem: SOUL_SAND

# Time in seconds until the pukeitems despawn, (mc default is 300 = 5 min) [60]
# If the item despawn time was changed in the spigot.yml, the pukeDespawntime changes as well.
pukeDespawntime: 60

# Consumable Item/strength. Decreases the alcohol level by <strength> when consumed. (list)
drainItems:
- BREAD/4
- MILK_BUCKET/2

# Time (in days) that drunkeness-data stays in memory after a player goes offline, to apply hangover etc. [7]
hangoverDays: 7

# Color the Item information (lore) depending on quality while it is 1. in a barrel and/or 2. in a brewing stand [true, true]
colorInBarrels: true
colorInBrewer: true

# Always show the 1-5 stars on the item depending on the quality. If false, they will only appear when brewing [true]
alwaysShowQuality: true

# Always show the alcohol content on the item. If false, it will only show in the brewing stand [false]
alwaysShowAlc: false

# If a Large Barrel can be opened by clicking on any of its blocks, not just Spigot or Sign. This is always true for Small Barrels. [true]
openLargeBarrelEverywhere: true

# How many Brewery drinks can be put into the Minecraft barrels [6]
maxBrewsInMCBarrels: 6

# The used Ingredients and other brewing-data is saved to all Brewery Items. To prevent
# hacked clients from reading what exactly was used to brew an item, the data can be encoded/scrambled.
# This is a fast process to stop players from hacking out recipes, once they get hold of a brew.
# Only drawback: brew items can only be used on another server with the same encodeKey.
# So enable this if you want to make recipe cheating harder, but don't share any brews by world download, schematics, or other means. [false]
enableEncode: false
encodeKey: 0

# Enable checking for Updates, Checks the curseforge api for updates to Brewery [true]
# If an Update is found a Message is logged on Server-start and displayed to OPs joining the game
updateCheck: true

# Autosave interval in minutes [3]
autosave: 3

# Show debug messages in log [false]
debug: false

# Config Version
version: '2.0'
oldMat: true



# -- Define custom items --
# The defined id can then be used in recipes

#  matchAny: true if it is already enough if one of the info matches
#  material: Which type the item has to be
#  name: Which name the item has to be (Formatting codes possible: such as &6)
#  lore: What has to be in the lore of the item

customItems:
  ex-item:
    # A Bedrock item called Wall and has the given line in its lore
    material: BEDROCK
    name: 'Wall'
    lore:
      - '&7Very well protected'

  ex-item2:
    # Using matchAny only one of the following has to match.
    # In this case on of the door types, or an item called Beechwood Door, or an item with 'A door' in its lore
    matchAny: true
    material:
      - WOODEN_DOOR
      - IRON_DOOR
    name:
      - 'Beechwood Door'
    lore:
      - 'A door'

  rasp:
    name: '&cRaspberry'


# -- Ingredients in the Cauldron --
# Which Ingredients are accepted by the Cauldron and the base potion resulting from them

 # name: Name of the base potion coming out of the Cauldron (Formatting codes possible: such as &6)
 # ingredients: List of 'material/amount'
 #   With an item in your hand, use /brew ItemName to get its material for use in a recipe
 #   (Item-ids instead of material are not supported by bukkit anymore and will not work)
 #   A list of materials can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
 # color: Color of the potion from a cauldron.
 #   Usable Colors: DARK_RED, RED, BRIGHT_RED, ORANGE, PINK, BLUE, CYAN, WATER, GREEN, BLACK, GREY, BRIGHT_GREY
 #   Or RGB colors (hex: for example '99FF33') (with '') (search for "HTML color" on the internet)
 # lore: List of additional text on the base potion. (Formatting codes possible: such as &6)

cauldron:
  ex:
    name: Example
    ingredients:
      - BEDROCK/2
      - DIAMOND
    color: BLACK
    lore:
      - An example for a Base Potion
      - This is how it comes out of a Cauldron

  # -- One Ingredient: --
  wheat:
    name: Fermented wheat
    ingredients: WHEAT

  sugarcane:
    name: Sugar brew
    ingredients: SUGAR_CANE
    color: 'f1ffad' # yellowish green

  apple:
    name: Apple cider
    ingredients: APPLE

  potato:
    name: Potatomash
    ingredients: POTATO_ITEM

  grass:
    name: Boiled herbs
    ingredients: LONG_GRASS
    color: '99ff66' # bright green

  rmushroom:
    name: Mushroom brew
    ingredients: RED_MUSHROOM
    color: 'ff5c33' # amber red

  cocoa:
    name: Chocolately brew
    ingredients: INK_SACK
    color: '804600' # mocca

  milk:
    name: Milky water
    ingredients: MILK_BUCKET
    color: BRIGHT_GREY

  # -- Multiple Ingredients: --
  apfelmet_base:
    name: Apple-Sugar brew
    ingredients:
      - SUGAR_CANE/3
      - APPLE
    color: 'e1ff4d' # greenish yellow



# -- Recipes for Potions --

# name: Different names for bad/normal/good (Formatting codes possible: such as &6)
# ingredients: List of 'material,data/amount'
#   With an item in your hand, use /brew ItemName to get its material for use in a recipe
#   (Item-ids instead of material are not supported by bukkit anymore and will not work)
#   A list of materials can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#   You can specify a data (durability) value, omitting it will ignore the data value of the added ingredient
#   Plugin items with 'plugin:id' (Currently supporting ExoticGarden, Slimefun, MMOItems, Brewery)
#   Or a custom item defined above
# cookingtime: Time in real minutes ingredients have to boil
# distillruns: How often it has to be distilled for full alcohol (0=without distilling)
# distilltime: How long (in seconds) one distill-run takes (0=Default time of 40 sec) MC Default would be 20 sec
# wood: Wood of the barrel 0=any 1=Birch 2=Oak 3=Jungle 4=Spruce 5=Acacia 6=Dark Oak
#   The Minecraft barrel is made of oak
# age: Time in Minecraft-days, the potion has to age in a barrel 0=no aging
# color: Color of the potion after distilling/aging.
#   Usable Colors: DARK_RED, RED, BRIGHT_RED, ORANGE, PINK, BLUE, CYAN, WATER, GREEN, BLACK, GREY, BRIGHT_GREY
#   Or RGB colors (hex: for example '99FF33') (with '') (search for "HTML color" on the internet)
# difficulty: 1-10 accuracy needed to get good quality (1 = unaccurate/easy, 10 = very precise/hard)
# alcohol: Absolute amount of alcohol 0-100 in a perfect potion (will be added directly to the player, where 100 means fainting)
# lore: List of additional text on the finished brew. (Formatting codes possible: such as &6)
#   Specific lore for quality possible, using + bad, ++ normal, +++ good, added to the front of the line.
# servercommands: List of Commands executed by the Server when drinking the brew
# playercommands: List of Commands executed by the Player when drinking the brew
# drinkmessage: Chat-message to the Player when drinking the Brew
# drinktitle: Title on Screen to the Player when drinking the Brew
# effects: List of effect/level/duration  Special potion-effect when drinking, duration in sek.
#   Suffix name with 'X' to hide effect from label. Sample: 'POISONX/2/10' (WEAKNESS, INCREASE_DAMAGE, SLOW and SPEED are always hidden.)
#   Effects are always hidden in 1.9 and newer, because of changes in the potion mechanics.
#   Possible Effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
#   Level or Duration ranges may be specified with a "-", ex. 'SPEED/1-2/30-40' = lvl 1 and 30 sec at worst and lvl 2 and 40 sec at best
#   Ranges also work high-low, ex. 'POISON/3-1/20-5' for weaker effects at good quality.
#   Highest possible Duration: 1638 sec. Instant Effects dont need any duration specified.

recipes:
#  Example Recipe with every possible entry first:
   ex:
      name: Bad Example/Example/Good Example
      ingredients:
      - DIAMOND/1
      - INK_SACK,3/20
      - WOOD,1/8
      - Brewery:Wheatbeer/2
#     - ExoticGarden:Grape/3
      - BEDROCK/1
      - ex-item/4
      cookingtime: 3
      distillruns: 2
      distilltime: 60
      wood: 4
      age: 11
      color: DARK_RED
      difficulty: 3
      alcohol: 23
      lore:
      - This is an examble brew
      - ++Just a normal Example
      - This text would be on the brew
      - + Smells disgusting
      - ++ Smells alright
      - +++ Smells really good
      servercommands:
      - weather clear
      playercommands:
      - homes
      drinkmessage: Tastes good
      drinktitle: Warms you from inside
      effects:
      - FIRE_RESISTANCE/20
      - HEAL/1
      - WEAKNESS/2-3/50-60
      - POISONX/1-0/20-0

   wheatbeer:
      name: Skunky Wheatbeer/Wheatbeer/Fine Wheatbeer
      ingredients:
      - WHEAT/3
      cookingtime: 8
      distillruns: 0
      wood: 1
      age: 2
      color: BRIGHT_GREY
      difficulty: 1
      alcohol: 5

   beer:
      name: Skunky Beer/Beer/Fine Beer
      ingredients:
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 0
      age: 3
      color: ORANGE
      difficulty: 1
      lore:
      - +++ &8Crisp taste
      alcohol: 6

   darkbeer:
      name: Skunky Darkbeer/Darkbeer/Fine Darkbeer
      ingredients:
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 4
      age: 8
      color: BLACK
      difficulty: 2
      lore:
      - +++ &8Roasted taste
      alcohol: 7

   mead:
      name: Awkward Mead/Mead/&6Golden Mead
      ingredients:
      - SUGAR_CANE/6
      cookingtime: 3
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 2
      lore:
      - +++ Has a golden shine
      alcohol: 9

   ap_mead:
      name: Apple Mead/Sweet Apple Mead/&6Sweet Golden Apple Mead
      ingredients:
      - SUGAR_CANE/6
      - APPLE/2
      cookingtime: 4
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 4
      alcohol: 12
      lore:
      - +Is there any Apple in this?
      - ++Refreshing taste of Apple
      - +++Sweetest hint of Apple
      effects:
      - WATER_BREATHINGX/1-2/150

   rum:
      name: Bitter Rum/Spicy Rum/&6Golden Rum
      ingredients:
      - SUGAR_CANE/14
      cookingtime: 5
      distillruns: 2
      distilltime: 30
      wood: 2
      age: 14
      color: DARK_RED
      difficulty: 6
      alcohol: 30
      effects:
      - FIRE_RESISTANCE/1/20-100
      - POISONX/1-0/30-0

   vodka:
      name: Lousy Vodka/Vodka/Russian Vodka
      ingredients:
      - POTATO_ITEM/10
      cookingtime: 15
      distillruns: 3
      age: 0
      color: BRIGHT_GREY
      difficulty: 4
      alcohol: 20
      lore: +&8Almost undrinkable
      effects:
      - WEAKNESS/15
      - POISON/10

   absinthe:
      name: Poor Absinthe/Absinthe/Strong Absinthe
      ingredients:
      - LONG_GRASS/15
      cookingtime: 3
      distillruns: 6
      distilltime: 80
      color: GREEN
      difficulty: 8
      alcohol: 45
      effects:
      - POISON/20-30

   potato_soup:
      name: Potato soup
      ingredients:
      - POTATO_ITEM/5
      - LONG_GRASS/3
      cookingtime: 3
      color: PINK
      difficulty: 1
      effects:
      - HEAL/0-1

   coffee:
      name: Stale Coffee/Coffee/Strong Coffee
      ingredients:
      - INK_SACK,3/12
      - MILK_BUCKET/2
      cookingtime: 2
      color: BLACK
      difficulty: 3
      lore: + &8Probably a week old
      effects:
      - REGENERATION/1/2-5
      - SPEED/1/30-140

# More Recipes ideas: Cachaca, Gin, Whiskey, Tequila, Cider, etc. as well as high quality abbreviations like golden vodka etc.
# I will not add more Recipes to the default config, as they would be public and viewable by users to cheat.
# It is up to the Serveradmin to change and add Recipes, so players cannot cheat from the default config.


# -- Plugin Compatibility --

# Enable checking of other Plugins (if installed) for Barrel Permissions [true]
useWorldGuard: true
useLWC: true
useGriefPrevention: true
useGMInventories: true
useCitadel: true

# Enable the Logging of Barrel Inventories to LogBlock [true]
useLogBlock: true


# -- Chat Distortion Settings --

# If written Chat is distorted when the Player is Drunk, so that it looks like drunk writing
# How much the chat is distorted depends on how drunk the Player is
# Below are settings for what and how changes in chat occur
enableChatDistortion: true

# Log to the Serverlog what the player actually wrote, before his words were altered [false]
logRealChat: false

# Text after specified commands will be distorted when drunk (list) [- /gl]
distortCommands:
- /gl
- /global
- /fl
- /s
- /letter
- /g
- /l
- /lokal
- /local
- /mail send
- /m
- /msg
- /w
- /whisper
- /reply
- /r
- /t
- /tell

# Distort the Text written on a Sign while drunk [false]
distortSignText: false

# Enclose a Chat text with these Letters to bypass Chat Distortion (Use "," as Separator) (list) [- '[,]']
# Chat Example: Hello i am drunk *I am testing Brewery*
distortBypass:
- '*,*'
- '[,]'

# words: Words and letters that will be altered when chatting while being drunk.
# Will be processed from first to last and a written sentece is altered in that order.

# replace: Word or letter to be replaced. (Special: "-space": replaces space, "-random": insert into random position, "-all": everything, "-start": At Beginning, "-end": At the End.)
# to: What to replace it with.
# pre: Words and Letters before the wanted word (split with ",")
# match: true = one of the "pre"-Words has to be before the wanted Word,  false = none of the "pre" Words is allowed before the wanted Word
# alcohol: 1-100 minimum drunkeness after which this word ist replaced
# percentage: Probability of replacing a Word in percent

words:
-  replace: s
   to: sh
   percentage: 90
   alcohol: 30

-  replace: ch
   to: sh
   pre: u,s,o,a
   match: false
   alcohol: 10
   percentage: 70

-  replace: h
   to: hh
   pre: sch,h,t
   match: false
   percentage: 60
   alcohol: 20

-  replace: th
   to: thl
   percentage: 40
   alcohol: 30

-  replace: sch
   to: shk
   percentage: 60
   alcohol: 40

-  replace: u
   to: uuh
   percentage: 20

-  replace: y
   to: yy
   percentage: 60
   alcohol: 15

-  replace: e
   to: ee
   percentage: 40
   alcohol: 15

-  replace: you
   to: u
   percentage: 40

-  replace: u
   to: uo
   pre: u
   match: false
   percentage: 60

-  replace: that
   to: taht
   percentage: 20
   alcohol: 40

-  replace: p
   to: b
   percentage: 30

-  replace: p
   to: b
   percentage: 70
   alcohol: 60

-  replace: up
   to: ubb
   percentage: 80
   alcohol: 25

-  replace: o
   to: oh
   percentage: 20

-  replace: ei
   to: i
   percentage: 30
   alcohol: 15

-  replace: b
   to: bb
   percentage: 80
   alcohol: 40

-  replace: '!!!'
   to: '!!!111!!!eleven!1!'
   pre: '!'
   match: false
   percentage: 20
   alcohol: 70

-  replace: '!'
   to: '!!'
   pre: '!'
   match: false
   percentage: 90

-  replace: drunk
   to: dhrkunn
   pre: are
   match: false
   percentage: 70
   alcohol: 65

-  replace: walk
   to: whhealhk
   pre: you can, you can still, you can not
   match: false
   percentage: 80
   alcohol: 30

-  replace: wtf
   to: wft
   percentage: 20
   alcohol: 40

-  replace: lol
   to: loool
   percentage: 80
   alcohol: 10

-  replace: afk
   to: aafkayyy
   percentage: 30
   alcohol: 30

-  replace: write
   to: wreitt
   pre: you can,you can still,you can not
   match: false
   percentage: 80
   alcohol: 50

-  replace: drink
   to: booze
   percentage: 80
   alcohol: 70

-  replace: '?'
   to: '????'
   pre: '?'
   match: false
   percentage: 80
   alcohol: 40

-  replace: -space
   to: ''
   pre: h,g,w
   match: true
   alcohol: 10

-  replace: -space
   to: ''
   percentage: 30
   alcohol: 35

-  replace: -space
   to: ''
   percentage: 10

-  replace: -start
   to: dho
   percentage: 15
   alcohol: 50

-  replace: -start
   to: hhn
   percentage: 10
   alcohol: 50

-  replace: -random
   to: lu
   percentage: 10

-  replace: -random
   to: lug
   percentage: 10
   alcohol: 50

-  replace: -random
   to: blub
   percentage: 20
   alcohol: 80

-  replace: -random
   to: lerg
   percentage: 40
   alcohol: 85

-  replace: -random
   to: gul
   percentage: 40
   alcohol: 80

-  replace: -random
   to: ' '
   percentage: 100
   alcohol: 70

-  replace: -random
   to: ' '
   percentage: 60
   alcohol: 40

-  replace: -random
   to: ' '
   percentage: 50
   alcohol: 30

-  replace: -end
   to: '!'
   percentage: 40
   alcohol: 30

-  replace: -random
   to: ' *hic* '
   percentage: 80
   alcohol: 70

-  replace: -random
   to: ' *hic* '
   percentage: 15
   alcohol: 40

-  replace: -space
   to: ' *hic* '
   percentage: 5
   alcohol: 20

-  replace: -end
   to: ' *hic*'
   percentage: 70
   alcohol: 50

-  replace: -all
   to: '*burp*'
   percentage: 3
   alcohol: 60

-  replace: -all
   to: '*burp*'
   percentage: 6
   alcohol: 80
