# config for Brewery.jar


# -- Settings --
# Defaults are written in []
# Deleting of single settings disables them

# Languagefile to be used (found in plugins/Brewery/languages)
language: en

# If the player wakes up at /home when logging in after excessive drinking (/home plugin must be installed!) [true]
enableHome: true

# Type of the home-teleport: ['cmd: home']
# bed = Player will be teleported to his spawn bed
# SamplePlugin = installed home plugin. Supports: ManagerXL. If not available:
# 'cmd: home' = /home will be executed by the player. He has to have permissions for it without any delay!
# 'cmd: spawn' = /spawn will be executed by the player.
# 'cmd: whatever' = /whatever will be executed by the player.
homeType: 'cmd: home'

# If the player "wakes up" at a random place when offline for some time while drinking (the places have to be defined with '/br Wakeup add' through an admin)
# The Player wakes at the nearest of two random places of his world [true]
enableWake: true

# If the Player may get some logins denied, when his character is drunk [true]
enableLoginDisallow: true

# If the Player faints (gets kicked) for some minutes if he overdrinks [true]
enableKickOnOverdrink: true

# If the Player vomits on high drunkeness (drops item defined below) [true]
# The item can not be collected and stays on the ground until it despawns. (Warning: May be collected after Server restart!)
enablePuke: true

# Item that is dropped multiple times uncollectable when puking [SOUL_SAND]
pukeItem: SOUL_SAND

# Consumable Item/strength. Decreases the alcohol level by <strength> when consumed. (list)
drainItems:
- BREAD/4
- MILK_BUCKET/2

# Time (in days) that drunkeness-data stays in memory after a player goes offline, to apply hangover etc. [7]
hangoverDays: 7

# Color the Item information (lore) depending on quality while it is 1. in a barrel and/or 2. in a brewing stand [true, false]
colorInBarrels: true
colorInBrewer: false

# If a Large Barrel can be opened by clicking on any of its blocks, not just Spigot or Sign. This is always true for Small Barrels. [true]
openLargeBarrelEverywhere: true

# Autosave interval in minutes [3]
autosave: 3

# Config Version
version: '1.2'


# -- Recipes for Potions --

# name: Different names for bad/normal/good (Formatting codes possible: such as &6)
# ingredients: List of material/amount
# cookingtime: Time in real minutes ingredients have to boil
# distillruns: How often it has to be distilled for full alcohol (0=without distilling)
# wood: Wood of the barrel 0=any 1=Birch 2=Oak 3=Jungle 4=Spruce
# age: Time in Minecraft-days, the potion has to age in a barrel 0=no aging
# color: Color of the potion after distilling/aging. DARK_RED, RED, BRIGHT_RED, ORANGE, PINK, BLUE, CYAN, WATER, GREEN, BLACK, GREY, BRIGHT_GREY
# difficulty: 1-10 accuracy needed to get good quality (1 = unaccurate/easy, 10 = very precise/hard)
# alcohol: Absolute amount of alcohol 0-100 in a perfect potion (will be added directly to the player, where 100 means fainting)
# effects: List of effect/duration  Special potion-effect when drinking, duration in sek. Suffix name with 'X' to hide effect from label. Sample: POISONX/10
#   (WEAKNESS, INCREASE_DAMAGE, SLOW and SPEED are always hidden.)  Possible Effects: http://jd.bukkit.org/rb/apidocs/org/bukkit/potion/PotionEffectType.html
#   instant effects (such as HEAL) _must!_ have defined the level instead of the duration!

recipes:
   1:
      name: Skunky Wheatbeer/Wheatbeer/Fine Wheatbeer
      ingredients: 
      - WHEAT/3
      cookingtime: 8
      distillruns: 0
      wood: 1
      age: 2
      color: BRIGHT_GREY
      difficulty: 1
      alcohol: 5
   2:
      name: Skunky Beer/Beer/Fine Beer
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 0
      age: 3
      color: ORANGE
      difficulty: 1
      alcohol: 6
   3:
      name: Skunky Darkbeer/Darkbeer/Fine Darkbeer
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 4
      age: 8
      color: BLACK
      difficulty: 2
      alcohol: 7
   4:
      name: Awkward Mead/Mead/&6Golden Mead
      ingredients: 
      - SUGAR_CANE/6
      cookingtime: 3
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 2
      alcohol: 9
   5:
      name: Apple Mead/Sweet Apple Mead/&6Sweet Golden Apple Mead
      ingredients: 
      - SUGAR_CANE/6
      - APPLE/2
      cookingtime: 4
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 4
      alcohol: 12
      effects:
      - WATER_BREATHINGX/150
   6:
      name: Bitter Rum/Spicy Rum/&6Golden Rum
      ingredients: 
      - SUGAR_CANE/14
      cookingtime: 5
      distillruns: 2
      wood: 2
      age: 14
      color: DARK_RED
      difficulty: 6
      alcohol: 30
      effects:
      - FIRE_RESISTANCE/100
   7:
      name: Lousy Vodka/Vodka/Russian Vodka
      ingredients: 
      - POTATO_ITEM/10
      cookingtime: 15
      distillruns: 3
      age: 0
      color: BRIGHT_GREY
      difficulty: 4
      alcohol: 20
      effects:
      - WEAKNESS/15
      - POISON/10
   8:
      name: Poor Absinthe/Absinthe/Strong Absinthe
      ingredients:
      - LONG_GRASS/15
      cookingtime: 3
      distillruns: 6
      color: GREEN
      difficulty: 8
      alcohol: 45
      effects:
      - POISON/20
   9:
      name: Potato soup
      ingredients:
      - POTATO_ITEM/5
      - LONG_GRASS/3
      cookingtime: 3
      color: PINK
      difficulty: 1
      effects:
      - HEAL/1



# cooked: EVERY possible ingredient and the names for the originating potions after fermenting:

cooked:
   WHEAT: Fermented wheat
   SUGAR_CANE: Sugar brew
   APPLE: Apple cider
   POTATO_ITEM: Potatomash
   LONG_GRASS: Boiled herbs
   RED_MUSHROOM: Mushroom brew




# -- Plugin Compatibility --

# Enable checking of other Plugins (if installed) for Barrel Permissions [true]
useWorldGuard: true
useLWC: true
useGriefPrevention: true

# Enable the Logging of Barrel Inventories to LogBlock
useLogBlock: true



# -- Chat Distortion Settings --

# Log to the Serverlog what the player actually wrote, before his words were altered [false]
logRealChat: false

# Text after specified commands will be distorted when drunk (list) [- /gl]
distortCommands:
- /gl
- /global
- /fl
- /s
- /letter

# Distort the Text written on a Sign while drunk [false]
distortSignText: false

# Enclose a text with these Letters to bypass Chat Distortion (Use "," as Separator) (list) [- '[,]']
distortBypass:
- '*,*'
- '[,]'

# words: Words and letters that will be altered when chatting while being drunk.
# Will be processed from first to last and a written sentece is altered in that order.

# replace: Word or letter to be replaced. (Special: "-space": replaces space, "-random": insert into random position, "-all": everything, "-start": At Beginning, "-end": At the End.)
# to: What to replace it with.
# pre: Words and Letters before the wanted word (split with ",")
# match: true = one of the "pre"-Words has to be before the wanted Word,  false = none of the "pre" Words is allowed before the wanted Word
# alcohol: 1-100 minimum drunkeness after which this word ist replaced
# percentage: Probability of replacing a Word in percent

words:
-  replace: s
   to: sh
   percentage: 90
   alcohol: 30

-  replace: ch
   to: sh
   pre: u,s,o,a
   match: false
   alcohol: 10
   percentage: 70

-  replace: h
   to: hh
   pre: sch,h,t
   match: false
   percentage: 60
   alcohol: 20

-  replace: th
   to: thl
   percentage: 40
   alcohol: 30

-  replace: sch
   to: shk
   percentage: 60
   alcohol: 40

-  replace: u
   to: uuh
   percentage: 20

-  replace: y
   to: yy
   percentage: 60
   alcohol: 15

-  replace: e
   to: ee
   percentage: 40
   alcohol: 15

-  replace: you
   to: u
   percentage: 40

-  replace: u
   to: uo
   pre: u
   match: false
   percentage: 60

-  replace: that
   to: taht
   percentage: 20
   alcohol: 40

-  replace: p
   to: b
   percentage: 30

-  replace: p
   to: b
   percentage: 70
   alcohol: 60

-  replace: up
   to: ubb
   percentage: 80
   alcohol: 25

-  replace: o
   to: oh
   percentage: 20

-  replace: ei
   to: i
   percentage: 30
   alcohol: 15

-  replace: b
   to: bb
   percentage: 80
   alcohol: 40

-  replace: '!!!'
   to: '!!!111!!!eleven!1!'
   pre: '!'
   match: false
   percentage: 20
   alcohol: 70

-  replace: '!'
   to: '!!'
   pre: '!'
   match: false
   percentage: 90

-  replace: drunk
   to: dhrkunn
   pre: are
   match: false
   percentage: 70
   alcohol: 65

-  replace: walk
   to: whhealhk
   pre: you can, you can still, you can not
   match: false
   percentage: 80
   alcohol: 30

-  replace: wtf
   to: wft
   percentage: 20
   alcohol: 40

-  replace: lol
   to: loool
   percentage: 80
   alcohol: 10

-  replace: afk
   to: aafkayyy
   percentage: 30
   alcohol: 30

-  replace: write
   to: wreitt
   pre: you can,you can still,you can not
   match: false
   percentage: 80
   alcohol: 50

-  replace: drink
   to: booze
   percentage: 80
   alcohol: 70

-  replace: '?'
   to: '????'
   pre: '?'
   match: false
   percentage: 80
   alcohol: 40

-  replace: -space
   to: ''
   pre: h,g,w
   match: true
   alcohol: 10

-  replace: -space
   to: ''
   percentage: 30
   alcohol: 35

-  replace: -space
   to: ''
   percentage: 10

-  replace: -start
   to: dho
   percentage: 15
   alcohol: 50

-  replace: -start
   to: hhn
   percentage: 10
   alcohol: 50

-  replace: -random
   to: lu
   percentage: 10

-  replace: -random
   to: lug
   percentage: 10
   alcohol: 50

-  replace: -random
   to: blub
   percentage: 20
   alcohol: 80

-  replace: -random
   to: lerg
   percentage: 40
   alcohol: 85

-  replace: -random
   to: gul
   percentage: 40
   alcohol: 80

-  replace: -random
   to: ' '
   percentage: 100
   alcohol: 70

-  replace: -random
   to: ' '
   percentage: 60
   alcohol: 40

-  replace: -random
   to: ' '
   percentage: 50
   alcohol: 30

-  replace: -end
   to: '!'
   percentage: 40
   alcohol: 30

-  replace: -random
   to: ' *hic* '
   percentage: 80
   alcohol: 70

-  replace: -random
   to: ' *hic* '
   percentage: 15
   alcohol: 40

-  replace: -space
   to: ' *hic* '
   percentage: 5
   alcohol: 20

-  replace: -end
   to: ' *hic*'
   percentage: 70
   alcohol: 50

-  replace: -all
   to: '*burp*'
   percentage: 3
   alcohol: 60

-  replace: -all
   to: '*burp*'
   percentage: 6
   alcohol: 80
